version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - microblog-net

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: microblog
      MYSQL_USER: microblog
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - microblog-net

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    environment:
      - SECRET_KEY=my-secret-key
      - MAIL_SERVER=smtp.googlemail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - DATABASE_URL=mysql+pymysql://microblog:${DATABASE_PASSWORD}@mysql/microblog
      - REDIS_URL=redis://redis:6379/0
    networks:
      - microblog-net
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis

  rq-worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=my-secret-key
      - MAIL_SERVER=smtp.googlemail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=true
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - DATABASE_URL=mysql+pymysql://microblog:${DATABASE_PASSWORD}@mysql/microblog
      - REDIS_URL=redis://redis:6379/0
    networks:
      - microblog-net
    depends_on:
      - mysql
      - redis
    entrypoint: venv/bin/rq
    command: worker -u redis://redis:6379/0 microblog-tasks

networks:
  microblog-net:
    driver: bridge
